### ISSUE TITLE
有没有更加详细的版本要求呢

### ISSUE THREAD

**Issue by EveningLin** [CaraJ7/MMSearch#2]
我的问题应该是来自于LLava对应的库，我是通过
`
git clone https://github.com/haotian-liu/LLaVA.git
cd LLaVA
pip install --upgrade pip  # enable PEP 660 support
pip install -e .
`
执行的，但是会报错
![image](https://github.com/user-attachments/assets/23ecc858-7610-444d-b188-54c902748285)

**Comment by CaraJ7** [comment]
哈喽，我们使用的是LLaVA-OneVision的[repo](https://github.com/LLaVA-VL/LLaVA-NeXT/tree/main)，按照repo里的说明安装即可。

**Comment by CaraJ7** [comment]
如果仍然报错欢迎重新打开issue

**Comment by EveningLin** [comment]
按照LLaVA-OneVision下载之后就ok了
其他环境报错还有解决都记录在下面咯
> ImportError: cannot import name 'field_validator' from 'pydantic' (/home/msai/li0082ng/anaconda3/envs/mmsearch/lib/python3.9/site-packages/pydantic/__init__.cpython-39-x86_64-linux-gnu.so)


`pip install -U pydantic`

> ImportError: FlashAttention2 has been toggled on, but it cannot be used due to the following error: the package flash_attn seems to be not installed. Please refer to the documentation of https://huggingface.co/docs/transformers/perf_infer_gpu_one#flashattention-2 to install Flash Attention 2.

` pip install flash-attn --no-build-isolation`

**Comment by cmengting** [comment]
> 哈喽，我们使用的是LLaVA-OneVision的[repo](https://github.com/LLaVA-VL/LLaVA-NeXT/tree/main)，按照repo里的说明安装即可。

Installed `llava-1.7.0.dev0` is ok.
