### ISSUE TITLE
How could I contribute my model onto this leaderboard?

### ISSUE THREAD

**Issue by zhimin-z** [CaraJ7/MMSearch#3]
![image](https://github.com/user-attachments/assets/2db248c9-89a0-4beb-9e9a-a189b9ac28f9)
I cannot find the specification in details in this repo.

**Comment by CaraJ7** [comment]
Hi @zhimin-z , please email your model's inference results of 4 tasks to jdzcarr7@gmail.com. Please also include the name of your model and a link of it (optional). We will update the leaderboard soon.

**Comment by zhimin-z** [comment]
> Hi @zhimin-z , please email your model's inference results of 4 tasks to [jdzcarr7@gmail.com](mailto:jdzcarr7@gmail.com). Please also include the name of your model and a link of it (optional). We will update the leaderboard soon.

Thanks, do you mean the prediction file? BTW, would you also update this information in the guideline as well?

**Comment by CaraJ7** [comment]
Yes, we will verify the result in the prediction fils of each task. The guidelines related to contributing to the leaderboard are updated.
